export const GET_STARWARS_SAGA = 'GET_STARWARS_SAGA';
export const GET_STARWARS_SUCCESS = 'GET_STARWARS_SUCCESS';
export const GET_STARWARS_ERROR = 'GET_STARWARS_ERROR';
export const GET_STARWARS_LOADING = 'GET_STARWARS_LOADING';
export const GET_STARWARS_CONFIRM = 'GET_STARWARS_CONFIRM';

export const GET_PLANETS_SAGA = 'GET_PLANETS_SAGA';
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
export const GET_PLANETS_ERROR = 'GET_PLANETS_ERROR';
export const GET_PLANETS_LOADING = 'GET_PLANETS_LOADING';
export const GET_PLANENTS_FORK = 'GET_PLANENTS_FORK';
export const GET_PLANENTS_CANCEL = 'GET_PLANENTS_CANCEL';
