export const GET_STARTWARS_REQUEST = 'GET_STARTWARS_REQUEST';
export const GET_STARWARS_SUCCESS = 'GET_STARWARS_SUCCESS';
export const GET_STARWARS_ERROR = 'GET_STARWARS_ERROR';
export const GET_STARWARS_LOADING = 'GET_STARWARS_LOADING';
